repos:
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
  - repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
  # Temporarily disabled ESLint hook due to CI issues
  # - repo: local
  #   hooks:
  #     - id: eslint
  #       name: eslint
  #       language: node
  #       entry: npm run lint
  #       types: [javascript]
  #       pass_filenames: false
