# Cookie-cutter helpers for demo apps.
# 1. create_csv_app() copies the tutorial script and sample data into a
#    destination folder, renaming the script to app.py. --with-api adds a
#    small FastAPI wrapper around the same data.
# 2. create_tailwind_ui() copies the auth-ui-kit directory to the
#    destination folder. --dark-mode selects the richer "enhanced" variant
#    (renamed to plain index.html/app.js) instead of the whole raw folder.
# 3. create_fullstack_app() combines both: the dark-mode UI as a frontend/
#    folder plus a backend/ FastAPI app, optionally with a minimal
#    HMAC-signed token auth layer (--auth) and SQLite-backed storage
#    instead of reading the CSV live on every request (--database). Neither
#    flag pulls in a new dependency - both are demo-grade, not
#    production-hardened, and say so in the generated code.
# All three functions return the path to the created directory.

from __future__ import annotations

from pathlib import Path
import shutil

_PACKAGE_ROOT = Path(__file__).resolve().parents[2]

_API_TEMPLATE = '''"""Generated by `gpt-fusion create_csv_app --with-api`.

Run with: uvicorn api:app --reload
Requires: pip install "gpt-fusion[backend]"
"""
from __future__ import annotations

from pathlib import Path

from fastapi import FastAPI

from gpt_fusion.analysis import average_from_csv, median_from_csv, load_numbers_from_csv

CSV_PATH = Path(__file__).parent / "numbers.csv"
app = FastAPI(title="CSV Analytics API")


@app.get("/")
def root() -> dict:
    return {"message": "CSV Analytics API - see /data, /average, and /median"}


@app.get("/data")
def data() -> dict:
    return {"values": load_numbers_from_csv(CSV_PATH)}


@app.get("/average")
def average() -> dict:
    return {"average": average_from_csv(CSV_PATH)}


@app.get("/median")
def median() -> dict:
    return {"median": median_from_csv(CSV_PATH)}
'''

_FULLSTACK_TEMPLATE_HEADER = '''"""Generated by
`gpt-fusion create_fullstack_app{flags_comment}`.

Run with: uvicorn app:app --reload
Requires: pip install "gpt-fusion[backend]"
"""
from __future__ import annotations

from pathlib import Path

from fastapi import FastAPI

CSV_PATH = Path(__file__).parent / "numbers.csv"
app = FastAPI(title="Fullstack Starter API")
'''

_DATABASE_TEMPLATE = """
# --- Storage: SQLite instead of reading the CSV on every request ---
# Demo-grade: one table, loaded once at startup. For a real app, use
# migrations and a proper ORM (see gpt_fusion.analysis for the CSV-only
# equivalent if you don't need this).
import csv
import sqlite3

DB_PATH = Path(__file__).parent / "app.db"


def _init_db() -> None:
    conn = sqlite3.connect(DB_PATH)
    conn.execute("CREATE TABLE IF NOT EXISTS numbers (value REAL)")
    if conn.execute("SELECT COUNT(*) FROM numbers").fetchone()[0] == 0:
        with open(CSV_PATH, newline="", encoding="utf-8") as f:
            rows = [(float(row["value"]),) for row in csv.DictReader(f)]
        conn.executemany("INSERT INTO numbers VALUES (?)", rows)
        conn.commit()
    conn.close()


def _get_numbers() -> list[float]:
    conn = sqlite3.connect(DB_PATH)
    values = [row[0] for row in conn.execute("SELECT value FROM numbers")]
    conn.close()
    return values


_init_db()
"""

_CSV_ONLY_TEMPLATE = """
# --- Storage: reads the CSV directly (pass --database for SQLite instead) ---
from gpt_fusion.analysis import load_numbers_from_csv


def _get_numbers() -> list[float]:
    return load_numbers_from_csv(CSV_PATH)
"""

_AUTH_TEMPLATE = """
# --- Auth: minimal HMAC-signed token, demo-grade only ---
# Not production auth: no refresh, no revocation, and the secret below
# must be replaced (e.g. via an environment variable) before shipping
# anywhere real. Shown as a self-contained example of the shape a real
# implementation would take, using only the standard library.
import base64
import hashlib
import hmac
import json
import time
from typing import Optional

from fastapi import Header, HTTPException
from pydantic import BaseModel

SECRET = "change-me-before-deploying-anywhere-real"
DEMO_USERNAME = "demo"
DEMO_PASSWORD = "demo123"
TOKEN_TTL_SECONDS = 3600


def _sign_token(payload: dict) -> str:
    body = base64.urlsafe_b64encode(json.dumps(payload).encode()).decode()
    signature = hmac.new(SECRET.encode(), body.encode(), hashlib.sha256).hexdigest()
    return f"{body}.{signature}"


def _verify_token(token: str) -> dict:
    try:
        body, signature = token.split(".")
        expected = hmac.new(SECRET.encode(), body.encode(), hashlib.sha256).hexdigest()
        if not hmac.compare_digest(signature, expected):
            raise ValueError("bad signature")
        payload = json.loads(base64.urlsafe_b64decode(body))
        if payload["exp"] < time.time():
            raise ValueError("expired")
        return payload
    except Exception as e:
        raise HTTPException(status_code=401, detail="Invalid or expired token") from e


class LoginRequest(BaseModel):
    username: str
    password: str


@app.post("/login")
def login(credentials: LoginRequest) -> dict:
    if credentials.username != DEMO_USERNAME or credentials.password != DEMO_PASSWORD:
        raise HTTPException(status_code=401, detail="Invalid credentials")
    expires_at = time.time() + TOKEN_TTL_SECONDS
    token = _sign_token({"sub": credentials.username, "exp": expires_at})
    return {"access_token": token, "token_type": "bearer"}


def _require_auth(authorization: Optional[str] = Header(None)) -> dict:
    if not authorization or not authorization.startswith("Bearer "):
        raise HTTPException(status_code=401, detail="Missing bearer token")
    return _verify_token(authorization.removeprefix("Bearer "))
"""

_FULLSTACK_ROUTES_TEMPLATE = """

@app.get("/")
def root() -> dict:
    return {"message": "Fullstack starter API - see /average and /median"}


@app.get("/average")
def average(__AUTH_PARAM__) -> dict:
    values = _get_numbers()
    return {"average": sum(values) / len(values) if values else None}


@app.get("/median")
def median(__AUTH_PARAM__) -> dict:
    values = sorted(_get_numbers())
    n = len(values)
    if n == 0:
        return {"median": None}
    mid = n // 2
    return {"median": values[mid] if n % 2 else (values[mid - 1] + values[mid]) / 2}
"""


def create_csv_app(dst: str | Path, with_api: bool = False) -> Path:
    """Create a minimal CSV demo in *dst* and return the path.

    Pass with_api=True to also generate api.py, a small FastAPI wrapper
    exposing the same data over /data, /average, and /median.
    """
    dst_path = Path(dst)
    dst_path.mkdir(parents=True, exist_ok=True)
    shutil.copy2(_PACKAGE_ROOT / "examples" / "tutorial.py", dst_path / "app.py")
    shutil.copy2(_PACKAGE_ROOT / "data" / "numbers.csv", dst_path / "numbers.csv")
    if with_api:
        (dst_path / "api.py").write_text(_API_TEMPLATE, encoding="utf-8")
    return dst_path


def create_tailwind_ui(dst: str | Path, dark_mode: bool = False) -> Path:
    """Create a Tailwind auth demo in *dst* and return the path.

    By default, copies the whole auth-ui-kit/ directory as-is (which
    already includes Tailwind dark: classes and a theme toggle). Pass
    dark_mode=True to instead generate just index.html + app.js from the
    visually richer "enhanced" variant (glass-effect UI, stronger dark
    theme), renamed to plain filenames.
    """
    dst_path = Path(dst)
    src = _PACKAGE_ROOT / "auth-ui-kit"
    if not dark_mode:
        shutil.copytree(src, dst_path, dirs_exist_ok=True)
        return dst_path

    dst_path.mkdir(parents=True, exist_ok=True)
    html = (src / "enhanced-index.html").read_text(encoding="utf-8")
    html = html.replace("enhanced-app.js", "app.js")
    (dst_path / "index.html").write_text(html, encoding="utf-8")
    shutil.copy2(src / "enhanced-app.js", dst_path / "app.js")
    return dst_path


def _build_fullstack_backend(auth: bool, database: bool) -> str:
    flags = []
    if auth:
        flags.append("--auth")
    if database:
        flags.append("--database")
    flags_comment = f" {' '.join(flags)}" if flags else ""

    source = _FULLSTACK_TEMPLATE_HEADER.format(flags_comment=flags_comment)
    source += _DATABASE_TEMPLATE if database else _CSV_ONLY_TEMPLATE
    if auth:
        source += _AUTH_TEMPLATE
        source = source.replace(
            "from fastapi import FastAPI\n",
            "from fastapi import Depends, FastAPI\n",
        )

    auth_param = "user: dict = Depends(_require_auth)" if auth else ""
    routes = _FULLSTACK_ROUTES_TEMPLATE.replace("__AUTH_PARAM__", auth_param)
    source += routes
    return source


def create_fullstack_app(
    dst: str | Path,
    auth: bool = False,
    database: bool = False,
) -> Path:
    """Create a combined frontend/ + backend/ starter app in *dst*.

    frontend/ is the dark-mode Tailwind auth UI (see create_tailwind_ui).
    backend/ is a FastAPI app serving the sample CSV data, optionally
    behind a minimal token-based auth layer (auth=True) and backed by
    SQLite instead of reading the CSV live (database=True). Returns the
    path to the created directory.
    """
    dst_path = Path(dst)
    dst_path.mkdir(parents=True, exist_ok=True)

    create_tailwind_ui(dst_path / "frontend", dark_mode=True)

    backend_dir = dst_path / "backend"
    backend_dir.mkdir(parents=True, exist_ok=True)
    shutil.copy2(_PACKAGE_ROOT / "data" / "numbers.csv", backend_dir / "numbers.csv")
    (backend_dir / "app.py").write_text(
        _build_fullstack_backend(auth=auth, database=database),
        encoding="utf-8",
    )

    return dst_path


__all__ = ["create_csv_app", "create_tailwind_ui", "create_fullstack_app"]


def _main() -> None:
    import argparse

    parser = argparse.ArgumentParser(description="Generate starter kit demos")
    sub = parser.add_subparsers(dest="cmd", required=True)

    csv_p = sub.add_parser("create_csv_app", help="Create the CSV demo")
    csv_p.add_argument("dest")
    csv_p.add_argument(
        "--with-api",
        action="store_true",
        help="Also generate api.py (FastAPI)",
    )

    ui_p = sub.add_parser("create_tailwind_ui", help="Create the Tailwind demo")
    ui_p.add_argument("dest")
    ui_p.add_argument(
        "--dark-mode",
        action="store_true",
        help="Use the enhanced, dark-mode-forward UI variant",
    )

    full_p = sub.add_parser(
        "create_fullstack_app",
        help="Create a combined frontend/ + backend/ app",
    )
    full_p.add_argument("dest")
    full_p.add_argument("--auth", action="store_true", help="Add a minimal auth layer")
    full_p.add_argument("--database", action="store_true", help="Use SQLite storage")

    args = parser.parse_args()
    if args.cmd == "create_csv_app":
        create_csv_app(args.dest, with_api=args.with_api)
    elif args.cmd == "create_tailwind_ui":
        create_tailwind_ui(args.dest, dark_mode=args.dark_mode)
    else:
        create_fullstack_app(args.dest, auth=args.auth, database=args.database)


if __name__ == "__main__":
    _main()
