# Plan:
# 1. Keep existing Jekyll config.
# 2. Add DocSearch placeholders for Algolia integration.
theme: jekyll-theme-cayman
title: GPT Fusion
description: Practical demos of human-AI collaboration
url: "https://costasford.github.io"
baseurl: "/gpt-fusion"
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
github:
  is_project_page: false
# DocSearch credentials are placeholders
docsearch:
  appId: "REPLACE_WITH_APP_ID"
  apiKey: "REPLACE_WITH_API_KEY"
  indexName: "gpt-fusion"
