# Plan: add jekyll-minifier to compress final site assets
source "https://rubygems.org"

gem "jekyll", "~> 4.2"
gem "jekyll-seo-tag"
gem "jekyll-sitemap"
gem "jekyll-theme-cayman"
gem "jekyll-minifier"
