name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Tweepy requires Python 3.10+, so drop 3.9 from the matrix
        python-version: ["3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
      - name: Install Ruby gems
        run: |
          gem install jekyll jekyll-theme-cayman jekyll-seo-tag jekyll-sitemap --no-document
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      - name: Install Node dependencies
        run: npm ci
      - name: Set up pre-commit
        run: pre-commit install
      - name: Lint
        run: pre-commit run --all-files
      - name: Test
        run: pytest --cov=src --cov-report=xml -q
      - name: Upload coverage
        uses: codecov/codecov-action@v3
      - name: Build documentation
        run: jekyll build -s docs -d docs/_site

  docs:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
      - name: Install Ruby gems
        run: |
          gem install jekyll jekyll-theme-cayman jekyll-seo-tag jekyll-sitemap --no-document
      - name: Build documentation
        run: jekyll build -s docs -d docs/_site
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: docs/_site

