name: CI

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Tweepy requires Python 3.10+, so drop 3.9 from the matrix
        python-version: ["3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
      - name: Install Ruby gems
        run: |
          cd docs
          bundle install
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
          pip install -e .
      - name: Install Node dependencies
        run: npm ci
      - name: Set up pre-commit
        run: pre-commit install
      - name: Lint
        run: pre-commit run --all-files
      - name: Test
        run: pytest --cov=src --cov-report=xml -q
      - name: Upload coverage
        uses: codecov/codecov-action@v3
      - name: Build documentation
        run: |
          cd docs
          JEKYLL_ENV=production bundle exec jekyll build -d _site
        if: matrix.python-version == '3.12'
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        if: matrix.python-version == '3.12'
        with:
          path: docs/_site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5

