name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
      - name: Install Ruby gems
        run: |
          gem install jekyll jekyll-theme-cayman --no-document
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      - name: Lint
        run: |
          black --check .
          flake8
      - name: Test
        run: pytest -q
      - name: Build documentation
        run: jekyll build -s docs -d docs/_site

