name: CI

permissions:
  contents: read

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Tweepy requires Python 3.10+, so drop 3.9 from the matrix
        python-version: ["3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
      - name: Install Ruby gems
        run: bundle install
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
          pip install -e .
      - name: Install Node dependencies
        run: npm ci
      - name: Set up pre-commit
        run: pre-commit install
      - name: Lint
        run: pre-commit run --all-files
      - name: Test
        run: pytest --cov=src --cov-report=xml -q
      - name: Upload coverage
        uses: codecov/codecov-action@v4
      - name: Build documentation
        run: JEKYLL_ENV=production bundle exec jekyll build
        if: matrix.python-version == '3.12'

